version: '3.8'

services:
  reactjs:
    build:
      context: ./frontend 
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Laravel Service
  laravel:
    build:
      context: ./backend 
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network

  # PostgreSQL Service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
